### ISSUE TITLE
allowSelfSigned not working for requestThingDescription

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#1268]
Not sure where to inquire for this: 

HttpConfig for https client seems to ignore allowSelfSigned:

```javascript
const { HttpsClientFactory } = require("@node-wot/binding-http");


const servient = new Servient();
servient.addClientFactory(new HttpsClientFactory({ 
        allowSelfSigned : true,
    }));

servient.start().then(async (WoT) => {
    const td = await WoT.requestThingDescription("https://localhost:8083/spectrometer/ocean-optics/USB2000-plus/resources/wot");
```

I get error:

FetchError: request to https://localhost:8083/spectrometer/ocean-optics/USB2000-plus/resources/wot failed, reason: self-signed certificate
    at ClientRequest.<anonymous> (H:\New Work\node-clients\serial-utility\node_modules\node-fetch\lib\index.js:1501:11)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'DEPTH_ZERO_SELF_SIGNED_CERT',
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}

_Originally posted by @VigneshVSV in https://github.com/eclipse-thingweb/node-wot/issues/177#issuecomment-2067688741_

**Comment by danielpeintner** [comment]
I looked into your problem and noticed that `allowSelfSigned` is not taken into account for `WoT.requestThingDescription(...)`. Instead it kicks in for interaction methods like `thing.readProperty(...)` only

**Comment by danielpeintner** [comment]
I created https://github.com/eclipse-thingweb/node-wot/pull/1269 which should fix the issue... I tested locally. if you can test/check also that would be great. Thanks!

**Comment by VigneshVSV** [comment]
I pulled the latest master branch and built the wot-bundle-min browser add-on. 

I still get the same error.


```javascript
// create servient - servients have both clients and servers - we are interested in the client
const servient = new Wot.Core.Servient();
const clientFactory = new Wot.Http.HttpsClientFactory({ allowSelfSigned : true });
servient.addClientFactory(clientFactory)
console.log("loaded WoT")

servient.start().then(async (WoT) => {
    // Then from here on you can consume the thing
    const td = await WoT.requestThingDescription("https://localhost:8083/spectrometer/ocean-optics/USB2000-plus/resources/wot-td");
    // let thing = await WoT.consume(td);
    // // thing.observeProperty("count", async (data) => { console.log("count:", await data.value()); });
    // console.log({
    //     serialNumber : await (await thing.readProperty("serial_number")).value(),
    //     model : await (await thing.readProperty("model")).value()
    // })

    // await thing.writeProperty("integration_time", {"value" : 1000})
    // await thing.invokeAction("start_acquisition")
  

}).catch((err) => { console.error(err); });
```

HTML:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Plotly Example</title>
    <!-- Include Plotly CDN -->
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script src="wot-bundle.min.js"></script>
    <script src="index.cjs" ></script>
</head>
<body>
    <!-- Your chart will be rendered here -->
    <div id="chart"></div>
</body>
</html>
```

**Comment by VigneshVSV** [comment]
Thanks, I built the browser bundle and it worked.
